CREATE TABLE app_user
(
    id           integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    username     VARCHAR2(255) NOT NULL CONSTRAINT username_uk UNIQUE,
    password     VARCHAR2(255),
    email        VARCHAR2(255) NOT NULL CONSTRAINT email_uk UNIQUE,
    first_name   VARCHAR2(255),
    last_name    VARCHAR2(255),
    phone_number VARCHAR2(255),
    enabled      NUMBER(1,0)
);

CREATE TABLE role
(
    id      integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    role    VARCHAR2(255) NOT NULL CONSTRAINT role_uk UNIQUE
);

CREATE TABLE user_role
(
    user_id      integer NOT NULL,
    role_id      integer NOT NULL,
    constraint PK_user_role primary key (user_id, role_id),
    CONSTRAINT FK_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT FK_role FOREIGN KEY (role_id) REFERENCES role(id)
);